name: news_blocks_ui
description: A Flutter package that contains UI components for news blocks.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.3 <4.0.0"
dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.3
  fake_async: ^1.3.0
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  mocktail_image_network: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
